### ISSUE TITLE
zcrmsdk import does not work

### ISSUE THREAD

**Issue by Jeeppler** [zoho/zcrm-python-sdk#1]
First I tried to just call `ZCRMRestClient.initialize()` which did not work:

~~~
>>> ZCRMRestClient.initialize() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ZCRMRestClient' is not defined
~~~

Second I tried to import the `zcrmsdk` and got the following error:

~~~
>>> import zcrmsdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/zcrmsdk/__init__.py", line 7, in <module>
    from RestClient import ZCRMRestClient
ImportError: No module named 'RestClient'
~~~

However, `RestClient.py` exists:

~~~
/usr/local/lib/python3.5/dist-packages/zcrmsdk# ls
CLException.py   Operations.py   Request.py     Utility.py
Handler.py       Org.py          Response.py    __init__.py
OAuthClient.py   Path.py         RestClient.py  __pycache__
OAuthUtility.py  Persistence.py  Test.py        resources
~~~

Do I miss anything?

**Comment by sp0gg** [comment]
The documentation at https://www.zoho.com/crm/help/developer/server-side-sdks/python.html states:

`Client app must have Python 2.7.`

I see from the above that you have pip installed to python3.5. If you try 2.7 it should work.

I also had to pip install `mysql-connector-python` to get the import working.

**Comment by Jeeppler** [comment]
@sp0gg you are right about this `Client app must have Python 2.7`. However, the `pip` package indicates that ZCRMSDK works with Python 2 and Python 3: https://pypi.python.org/pypi/zcrmsdk/1.0.0

I will try this `mysql-connector-python` let's see maybe it works.

**Comment by sp0gg** [comment]
The PyPI documentation is incorrect. I received the same error you did when I ran the client on Python 3. The library will need updates to work with Python 3.

**Comment by Jeeppler** [comment]
@sp0gg thanks for letting me know.
